services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    expose:
      - "8001"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
