# Generated by Django 5.0.14 on 2025-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepermission',
            name='table',
            field=models.CharField(choices=[('table1', 'Table 1'), ('table2', 'Table 2'), ('report', 'Report')], max_length=10),
        ),
    ]
