# Generated by Django 5.0.14 on 2025-06-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0002_alter_tablepermission_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablepermission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
