# Generated by Django 5.0.14 on 2025-07-03 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0003_tablepermission_can_edit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PvoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20, unique=True)),
                ('fecha_full', models.DateField(blank=True, null=True)),
                ('fecha_flp', models.DateTimeField(blank=True, null=True)),
                ('fecha_fef', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tableapp_pvoregistro',
                'managed': True,
            },
        ),
    ]
