# Generated by Django 5.0.14 on 2025-07-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0004_pvoregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepermission',
            name='table',
            field=models.CharField(choices=[('table1', 'Table 1'), ('table2', 'Table 2'), ('report', 'Report'), ('edit_dates', 'Edit Dates')], max_length=10),
        ),
    ]
