# Generated by Django 5.0.14 on 2025-07-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_alter_tablepermission_table'),
    ]

    operations = [
    ]
