# Generated by Django 5.0.14 on 2025-07-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0006_sync_tablepermission_columns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
        migrations.DeleteModel(
            name='Table2',
        ),
        migrations.AddField(
            model_name='tablepermission',
            name='can_edit_fef',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablepermission',
            name='can_edit_flp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablepermission',
            name='can_edit_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='fecha_fef',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='fecha_flp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tablepermission',
            name='table',
            field=models.CharField(choices=[('report', 'Report'), ('edit_dates', 'Edit Dates')], max_length=20),
        ),
    ]
