# Generated by Django 5.0.14 on 2025-08-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0008_tablepermission_can_view_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='fecha_fif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='fecha_fif',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablepermission',
            name='can_edit_fif',
            field=models.BooleanField(default=False),
        ),
    ]
