# Generated by Django 5.0.14 on 2025-08-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0009_historicalpvoregistro_fecha_fif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tableapp_fpcatalogo',
            },
        ),
        migrations.CreateModel(
            name='FPConfig',
            fields=[
                ('codigo_producto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado_fp', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_fp_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('familia', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('planta', models.CharField(blank=True, max_length=50, null=True)),
                ('tamano_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_fase', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tableapp_fpconfig',
            },
        ),
    ]
