# Generated by Django 5.0.14 on 2025-08-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0010_fpcatalogo_fpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='batch',
            field=models.IntegerField(blank=True, db_column='BATCH', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='f_acondicionamiento',
            field=models.DateField(blank=True, db_column='F_ACONDICIONAMIENTO', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='f_despacho',
            field=models.DateField(blank=True, db_column='F_DESPACHO', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='f_dispensacion',
            field=models.DateField(blank=True, db_column='F_DISPENSACION', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='f_embalaje',
            field=models.DateField(blank=True, db_column='F_EMBALAJE', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='f_enfriamiento',
            field=models.DateField(blank=True, db_column='F_ENFRIAMIENTO', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='f_envasado',
            field=models.DateField(blank=True, db_column='F_ENVASADO', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='f_fabricacion',
            field=models.DateField(blank=True, db_column='F_FABRICACION', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='f_pesaje',
            field=models.DateField(blank=True, db_column='F_PESAJE', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='familia',
            field=models.CharField(blank=True, db_column='FAMILIA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='p_acondicionamiento',
            field=models.IntegerField(blank=True, db_column='P_ACONDICIONAMIENTO', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='p_despacho',
            field=models.IntegerField(blank=True, db_column='P_DESPACHO', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='p_dispensacion',
            field=models.IntegerField(blank=True, db_column='P_DISPENSACION', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='p_embalaje',
            field=models.IntegerField(blank=True, db_column='P_EMBALAJE', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='p_enfriamiento',
            field=models.IntegerField(blank=True, db_column='P_ENFRIAMIENTO', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='p_envasado',
            field=models.IntegerField(blank=True, db_column='P_ENVASADO', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='p_fabricacion',
            field=models.IntegerField(blank=True, db_column='P_FABRICACION', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='p_pesaje',
            field=models.IntegerField(blank=True, db_column='P_PESAJE', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='planta',
            field=models.CharField(blank=True, db_column='PLANTA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='pt',
            field=models.CharField(blank=True, db_column='PT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='t_acondicionamiento',
            field=models.DecimalField(blank=True, db_column='T_ACONDICIONAMIENTO', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='t_despacho',
            field=models.DecimalField(blank=True, db_column='T_DESPACHO', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='t_dispensacion',
            field=models.DecimalField(blank=True, db_column='T_DISPENSACION', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='t_embalaje',
            field=models.DecimalField(blank=True, db_column='T_EMBALAJE', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='t_enfriamiento',
            field=models.DecimalField(blank=True, db_column='T_ENFRIAMIENTO', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='t_envasado',
            field=models.DecimalField(blank=True, db_column='T_ENVASADO', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='t_fabricacion',
            field=models.DecimalField(blank=True, db_column='T_FABRICACION', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='t_pesaje',
            field=models.DecimalField(blank=True, db_column='T_PESAJE', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='tamano_lote',
            field=models.IntegerField(blank=True, db_column='TAMANO_LOTE', null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='tipo',
            field=models.CharField(blank=True, db_column='TIPO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='batch',
            field=models.IntegerField(blank=True, db_column='BATCH', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='f_acondicionamiento',
            field=models.DateField(blank=True, db_column='F_ACONDICIONAMIENTO', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='f_despacho',
            field=models.DateField(blank=True, db_column='F_DESPACHO', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='f_dispensacion',
            field=models.DateField(blank=True, db_column='F_DISPENSACION', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='f_embalaje',
            field=models.DateField(blank=True, db_column='F_EMBALAJE', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='f_enfriamiento',
            field=models.DateField(blank=True, db_column='F_ENFRIAMIENTO', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='f_envasado',
            field=models.DateField(blank=True, db_column='F_ENVASADO', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='f_fabricacion',
            field=models.DateField(blank=True, db_column='F_FABRICACION', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='f_pesaje',
            field=models.DateField(blank=True, db_column='F_PESAJE', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='familia',
            field=models.CharField(blank=True, db_column='FAMILIA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='p_acondicionamiento',
            field=models.IntegerField(blank=True, db_column='P_ACONDICIONAMIENTO', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='p_despacho',
            field=models.IntegerField(blank=True, db_column='P_DESPACHO', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='p_dispensacion',
            field=models.IntegerField(blank=True, db_column='P_DISPENSACION', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='p_embalaje',
            field=models.IntegerField(blank=True, db_column='P_EMBALAJE', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='p_enfriamiento',
            field=models.IntegerField(blank=True, db_column='P_ENFRIAMIENTO', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='p_envasado',
            field=models.IntegerField(blank=True, db_column='P_ENVASADO', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='p_fabricacion',
            field=models.IntegerField(blank=True, db_column='P_FABRICACION', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='p_pesaje',
            field=models.IntegerField(blank=True, db_column='P_PESAJE', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='planta',
            field=models.CharField(blank=True, db_column='PLANTA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='pt',
            field=models.CharField(blank=True, db_column='PT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='t_acondicionamiento',
            field=models.DecimalField(blank=True, db_column='T_ACONDICIONAMIENTO', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='t_despacho',
            field=models.DecimalField(blank=True, db_column='T_DESPACHO', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='t_dispensacion',
            field=models.DecimalField(blank=True, db_column='T_DISPENSACION', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='t_embalaje',
            field=models.DecimalField(blank=True, db_column='T_EMBALAJE', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='t_enfriamiento',
            field=models.DecimalField(blank=True, db_column='T_ENFRIAMIENTO', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='t_envasado',
            field=models.DecimalField(blank=True, db_column='T_ENVASADO', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='t_fabricacion',
            field=models.DecimalField(blank=True, db_column='T_FABRICACION', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='t_pesaje',
            field=models.DecimalField(blank=True, db_column='T_PESAJE', decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='tamano_lote',
            field=models.IntegerField(blank=True, db_column='TAMANO_LOTE', null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='tipo',
            field=models.CharField(blank=True, db_column='TIPO', max_length=50, null=True),
        ),
    ]
