# Generated by Django 5.0.14 on 2025-08-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0011_historicalpvoregistro_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpvoregistro',
            name='f_acondicionamiento',
            field=models.CharField(blank=True, db_column='F_ACONDICIONAMIENTO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpvoregistro',
            name='f_despacho',
            field=models.CharField(blank=True, db_column='F_DESPACHO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpvoregistro',
            name='f_dispensacion',
            field=models.CharField(blank=True, db_column='F_DISPENSACION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpvoregistro',
            name='f_embalaje',
            field=models.CharField(blank=True, db_column='F_EMBALAJE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpvoregistro',
            name='f_enfriamiento',
            field=models.CharField(blank=True, db_column='F_ENFRIAMIENTO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpvoregistro',
            name='f_envasado',
            field=models.CharField(blank=True, db_column='F_ENVASADO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpvoregistro',
            name='f_fabricacion',
            field=models.CharField(blank=True, db_column='F_FABRICACION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpvoregistro',
            name='f_pesaje',
            field=models.CharField(blank=True, db_column='F_PESAJE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='f_acondicionamiento',
            field=models.CharField(blank=True, db_column='F_ACONDICIONAMIENTO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='f_despacho',
            field=models.CharField(blank=True, db_column='F_DESPACHO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='f_dispensacion',
            field=models.CharField(blank=True, db_column='F_DISPENSACION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='f_embalaje',
            field=models.CharField(blank=True, db_column='F_EMBALAJE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='f_enfriamiento',
            field=models.CharField(blank=True, db_column='F_ENFRIAMIENTO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='f_envasado',
            field=models.CharField(blank=True, db_column='F_ENVASADO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='f_fabricacion',
            field=models.CharField(blank=True, db_column='F_FABRICACION', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pvoregistro',
            name='f_pesaje',
            field=models.CharField(blank=True, db_column='F_PESAJE', max_length=50, null=True),
        ),
    ]
