# Generated by Django 5.0.14 on 2025-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0012_alter_historicalpvoregistro_f_acondicionamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpconfig',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
