# Generated by Django 5.0.14 on 2025-09-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0013_fpconfig_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='obs_fef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='obs_flp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpvoregistro',
            name='obs_full',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='obs_fef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='obs_flp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pvoregistro',
            name='obs_full',
            field=models.TextField(blank=True, null=True),
        ),
    ]
